apiVersion: v1
kind: Service
metadata:
  name: issuance-svc
  namespace: kube-credential
spec:
  selector:
    app: issuance-svc
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
