apiVersion: v1
kind: Service
metadata:
  name: verification-svc
  namespace: kube-credential
spec:
  selector:
    app: verification-svc
  ports:
    - name: http
      port: 80
      targetPort: 3001
  type: ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: verification-svc
  namespace: kube-credential
spec:
  selector:
    app: verification-svc
  ports:
    - name: http
      port: 80
      targetPort: 3001
  type: ClusterIP
