apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-credential
  namespace: kube-credential
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: YOUR-DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: web-svc, port: { number: 80 } }
          - path: /issue
            pathType: Prefix
            backend:
              service: { name: issuance-svc, port: { number: 80 } }
          - path: /verify
            pathType: Prefix
            backend:
              service: { name: verification-svc, port: { number: 80 } }
